### Upload image to a post
POST http://localhost:3000/posts/5e263872-37df-4f00-92e9-9ac53d2cfea8/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NmE4Mjc4YS0yM2MwLTQ0YjctYWQwMS1mNWYzMzU5ZDMxODEiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc1MTM4MjI4OSwiZXhwIjoxNzUxMzg1ODg5fQ.UXI-6b2kmVvp2rnKdf8MNdhfdkYOkTHzBttIx16ur9k
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="image"; filename="IMG_20250501_160120973.jpg"
Content-Type: image/jpeg

< ./relative_path.jpg
------WebKitFormBoundary--